### ISSUE TITLE
Agent should export node ips in pod status 

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/agent#223]
In order for service discovery based on pods to work for collecting metrics via Prometheus or Victoriametrics our pods need to publish ip addresses in the status field.

This excerpt shows what a kubernetes pod sets, a first trial with both hostIP and podIP was successful.

```yaml
apiVersion: v1
kind: Pod
metadata:
...
spec:
...
status:
 ...
  hostIP: 10.10.92.14
  podIP: 10.42.0.6
  podIPs:
  - ip: 10.42.0.6
```

We should further investigate, what field Prometheus actually uses and if there are reasons to set both.
