### ISSUE TITLE
Agent doesn't replace variables in environment variables 

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/agent#29]
The agent replaces three paths in config files that are downloaded from config maps:

- configroot
- logroot
- packageroot

These replacements should also happen in environment variables that are added to pods (see below for an example), but this is not currently working.

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-12-14T12:48:19Z"
  generateName: spark-cluster-worker-
spec:
  containers:
  - command:
    - spark-3.0.1-bin-hadoop2.7/sbin/start-slave.sh
    - spark://bawa-virtualbox:7077
    env:
    - name: SPARK_CONF_DIR
      value: '{{configroot}}/conf'
    - name: SPARK_NO_DAEMONIZE
      value: "true"
    image: spark:3.0.1
    imagePullPolicy: IfNotPresent
    name: spark-3-0-1
```
