### ISSUE TITLE
Crash if no tag is provided for the container image

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/agent#39]
The agent crashes if no tag is provided for the container image.

Given the following `kafka.yaml`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kafka
spec:
  containers:
  - name: kafka
    image: kafka
  tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "stackable-linux"
```

When the pod is deployed:
```sh
$ kubectl apply -f kafka.yml
```

Then the agent crashes with the following log output:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/provider/repository/package.rs:42:35
```
